apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-rms-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pet-rms-docker-img
  template:
    metadata:
      labels:
        app: pet-rms-docker-img
    spec:
      containers:
      - name: rms-container

        image: dariusfoo11/pet-rms-docker-img:v4

        ports:
        - containerPort: 5050
